---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@8b7a3cbe3cf354dcb78a7ae17b16ecb5f5b17211 # main
    name: GitHub Release
