---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@8b7a3cbe3cf354dcb78a7ae17b16ecb5f5b17211 # main
    name: Module Validation
    with:
      working-directory: .
